refactored building risk assessment and added building entity
GeoffA12/building-risk-management-back-end pull request #10
Opened 2020-11-19 18:29 UTC by rfitzgerald11

2020-11-19 18:33 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/models/building/Building.java
> +
Why no constructor here?

2020-11-19 18:34 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/models/buildingriskassessment/BuildingRiskAssessment.java
> +public class BuildingRiskAssessment {
I think we might need to change this model name to `BuildingRiskAssessments` since there can be multiple risk assessments at a building.

2020-11-19 18:35 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/models/buildingriskassessment/BuildingRiskAssessment.java
>  @Document(collection = "buildingriskassessment")
Same comments as below

2020-11-19 18:36 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/repositories/BuildingRepository.java
> +public interface BuildingRepository extends MongoRepository<Building, String> {
What type of custom queries do you think we could use with buildings? Probably not the most important thing right now but eventually we'd probably want to add some custom queries here.

2020-11-19 18:37 UTC, GeoffA12 requested changes
Looks pretty good, left some smaller comments to look at.

2020-11-19 18:42 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/models/building/Building.java
> +@Document(collection = "building")
These models need to implement the `Entity` interface.

2020-11-19 18:42 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/models/buildingriskassessment/BuildingRiskAssessment.java
> +public class BuildingRiskAssessment {
Need to implement the Entity interface.

2020-11-19 18:43 UTC, GeoffA12 requested changes
Interface comments

2020-11-24 18:38 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/models/building/input/GetAllBuildingsBySiteInput.java
> +public class GetAllBuildingsBySiteInput {
Please reuse the `GetEntityBySiteInput` class. This can be removed.

2020-11-24 18:41 UTC, GeoffA12 reviewed
Please add some test cases in the PR Comments

2020-11-26 08:01 UTC, rfitzgerald11 commented
/createBuilding
Input: `{"publisherId": "08u08dhaoufdg", "name": "John Brooks Williams - South", "code": "JBWS", "siteId": "24eb7e16-9a52-47fc-bc5d-47a4aa0492bb", "address": {"street": "3001 S Congress Ave", "city": "Austin", "state": "TX"}}`

Output: `{"id":"80e005f1-0cc1-4a59-bb4a-b2e01ea1e1bf","createdAt":"2020-11-26T07:45:12.3148652","updatedAt":"2020-11-26T07:45:12.3148652","entityTrail":[{"timestamp":"2020-11-26T07:45:12.3148652","userId":"08u08dhaoufdg","systemComment":"CREATED BUILDING"}],"publisherId":"08u08dhaoufdg","name":"John Brooks Williams - South","code":"JBWS","siteId":"24eb7e16-9a52-47fc-bc5d-47a4aa0492bb","buildingRiskAssessmentIds":[],"address":{"street":"3001 S Congress Ave","city":"Austin","state":"TX"}}`

/updateBuilding
Input: `{"id": "80e005f1-0cc1-4a59-bb4a-b2e01ea1e1bf","publisherId": "08u08dhaoufdg", "name": "John Brooks Williams Science Center - South", "code": "JBWS", "siteId": "24eb7e16-9a52-47fc-bc5d-47a4aa0492bb", "address": {"street": "3001 S Congress Ave Building JBWS", "city": "Austin", "state": "TX"}}`

Output: `{"id":"80e005f1-0cc1-4a59-bb4a-b2e01ea1e1bf","createdAt":"2020-11-26T07:45:12.314","updatedAt":"2020-11-26T07:50:39.6312776","entityTrail":[{"timestamp":"2020-11-26T07:45:12.314","userId":"08u08dhaoufdg","systemComment":"CREATED BUILDING"},{"timestamp":"2020-11-26T07:50:39.7780468","userId":"08u08dhaoufdg","systemComment":"UPDATED BUILDING"}],"publisherId":"08u08dhaoufdg","name":"John Brooks Williams Science Center - South","code":"JBWS","siteId":"24eb7e16-9a52-47fc-bc5d-47a4aa0492bb","buildingRiskAssessmentIds":[],"address":{"street":"3001 S Congress Ave Building JBWS","city":"Austin","state":"TX"}}`

/deleteBuilding
Input: `http://localhost:8080/deleteBuilding?id=45e52bd6-22ab-4ab3-83a4-82364d5e14d2`

Output: `Deleted: Building{id='45e52bd6-22ab-4ab3-83a4-82364d5e14d2', createdAt=2020-11-26T07:44:32.413, updatedAt=2020-11-26T07:44:32.413, entityTrail=[EntityTrail{timestamp=2020-11-26T07:44:32.413, userId='08u08dhaoufdg', systemComment='CREATED BUILDING'}], publisherId='08u08dhaoufdg', name='John Brooks Williams - North', code='JBWN', siteId='24eb7e16-9a52-47fc-bc5d-47a4aa0492bb', buildingRiskAssessmentIds=[], address=Address{street='3001 S Congress Ave', city='Austin', state='TX'}} from building repository`

/getBuildingById
Input: `http://localhost:8080/getBuildingById?id=80e005f1-0cc1-4a59-bb4a-b2e01ea1e1bf`

Output: `{"id":"80e005f1-0cc1-4a59-bb4a-b2e01ea1e1bf","createdAt":"2020-11-26T07:45:12.314","updatedAt":"2020-11-26T07:50:39.631","entityTrail":[{"timestamp":"2020-11-26T07:45:12.314","userId":"08u08dhaoufdg","systemComment":"CREATED BUILDING"},{"timestamp":"2020-11-26T07:50:39.778","userId":"08u08dhaoufdg","systemComment":"UPDATED BUILDING"}],"publisherId":"08u08dhaoufdg","name":"John Brooks Williams Science Center - South","code":"JBWS","siteId":"24eb7e16-9a52-47fc-bc5d-47a4aa0492bb","buildingRiskAssessmentIds":[],"address":{"street":"3001 S Congress Ave Building JBWS","city":"Austin","state":"TX"}}`

/getBuildingsBySite
Input: `{"associatedSiteIds": ["24eb7e16-9a52-47fc-bc5d-47a4aa0492bb"]}`

Output: `[{"id":"80e005f1-0cc1-4a59-bb4a-b2e01ea1e1bf","createdAt":"2020-11-26T07:45:12.314","updatedAt":"2020-11-26T07:50:39.631","entityTrail":[{"timestamp":"2020-11-26T07:45:12.314","userId":"08u08dhaoufdg","systemComment":"CREATED BUILDING"},{"timestamp":"2020-11-26T07:50:39.778","userId":"08u08dhaoufdg","systemComment":"UPDATED BUILDING"}],"publisherId":"08u08dhaoufdg","name":"John Brooks Williams Science Center - South","code":"JBWS","siteId":"24eb7e16-9a52-47fc-bc5d-47a4aa0492bb","buildingRiskAssessmentIds":[],"address":{"street":"3001 S Congress Ave Building JBWS","city":"Austin","state":"TX"}}]`

2020-11-26 23:36 UTC, GeoffA12 commented
/createBuildingRiskAssessment Input
```
curl -i -X POST -H 'Content-type: application/json' -d '{ "publisherId": "a2da8355-1429-4005-ba36-1f5cf45938af", "riskAssessmentIds": [ "8c2bcb33-5665-47d4-a90b-4c6b2f06e065", "2c744687-5c27-40ed-a92c-be0438b43455"], "siteMaintenanceAssociateIds": ["9bafaef1-53e4-44f2-b191-00a86d9d85ba"], "buildingId": "048866c1-ff5b-4b5d-8aae-accb9337ff1f", "title": "JBWS Building Assessment 1", "description": "JBWS Building Assessment for COVID-19 protocols from OSHA", "workOrder": 45 }' http://localhost:8080/createBuildingRiskAssessment
```

Output: 
```
{"id":"dec2db38-7e83-45e8-a1d1-a2ee2967257c","createdAt":"2020-11-26T22:52:52.125937","updatedAt":"2020-11-26T22:52:52.125937","entityTrail":[{"timestamp":"2020-11-26T22:52:52.125937","userId":"a2da8355-1429-4005-ba36-1f5cf45938af","systemComment":"CREATED BUILDING RISK ASSESSMENT"}],"publisherId":"a2da8355-1429-4005-ba36-1f5cf45938af","riskAssessmentIds":["8c2bcb33-5665-47d4-a90b-4c6b2f06e065","2c744687-5c27-40ed-a92c-be0438b43455"],"buildingId":"048866c1-ff5b-4b5d-8aae-accb9337ff1f","title":"JBWS Building Assessment 1","description":"JBWS Building Assessment for COVID-19 protocols from OSHA"}
```

/updateBuildingRiskAssessment
```
curl -i -X POST -H 'Content-type: application/json' -d '{ "publisherId": "a2da8355-1429-4005-ba36-1f5cf45938af", "riskAssessmentIds": [ "8c2bcb33-5665-47d4-a90b-4c6b2f06e065", "2c744687-5c27-40ed-a92c-be0438b43455"], "siteMaintenanceAssociateIds": ["9bafaef1-53e4-44f2-b191-00a86d9d85ba"], "buildingId": "048866c1-ff5b-4b5d-8aae-accb9337ff1f", "id": "dec2db38-7e83-45e8-a1d1-a2ee2967257c", "title": "JBWS Building Assessment 2", "description": "JBWS Building Assessment for COVID-19 protocols from OSHA and CDC", "workOrder": 46 }' http://localhost:8080/updateBuildingRiskAssessment
```

Output:
```
{"id":"dec2db38-7e83-45e8-a1d1-a2ee2967257c","createdAt":"2020-11-26T22:52:52.125","updatedAt":"2020-11-26T22:57:36.375138","entityTrail":[{"timestamp":"2020-11-26T22:52:52.125","userId":"a2da8355-1429-4005-ba36-1f5cf45938af","systemComment":"CREATED BUILDING RISK ASSESSMENT"},{"timestamp":"2020-11-26T22:57:36.375138","userId":"a2da8355-1429-4005-ba36-1f5cf45938af","systemComment":"UPDATED BUILDING RISK ASSESSMENT"}],"publisherId":"a2da8355-1429-4005-ba36-1f5cf45938af","riskAssessmentIds":["8c2bcb33-5665-47d4-a90b-4c6b2f06e065","2c744687-5c27-40ed-a92c-be0438b43455"],"buildingId":"048866c1-ff5b-4b5d-8aae-accb9337ff1f","title":"JBWS Building Assessment 2","description":"JBWS Building Assessment for COVID-19 protocols from OSHA and CDC"}
```

/getBuildingRiskAssessmentById Input
```
curl -i -X GET "http://localhost:8080/getBuildingRiskAssessmentById?id=dec2db38-7e83-45e8-a1d1-a2ee2967257c"
```

Output: 
```
{"id":"dec2db38-7e83-45e8-a1d1-a2ee2967257c","createdAt":"2020-11-26T22:52:52.125","updatedAt":"2020-11-26T22:57:36.375","entityTrail":[{"timestamp":"2020-11-26T22:52:52.125","userId":"a2da8355-1429-4005-ba36-1f5cf45938af","systemComment":"CREATED BUILDING RISK ASSESSMENT"},{"timestamp":"2020-11-26T22:57:36.375","userId":"a2da8355-1429-4005-ba36-1f5cf45938af","systemComment":"UPDATED BUILDING RISK ASSESSMENT"}],"publisherId":"a2da8355-1429-4005-ba36-1f5cf45938af","riskAssessmentIds":["8c2bcb33-5665-47d4-a90b-4c6b2f06e065","2c744687-5c27-40ed-a92c-be0438b43455"],"buildingId":"048866c1-ff5b-4b5d-8aae-accb9337ff1f","title":"JBWS Building Assessment 2","description":"JBWS Building Assessment for COVID-19 protocols from OSHA and CDC"}
```

/getBulidingRiskAssessmentsBySite Input
```
curl -i -X POST -H 'Content-type: application/json' -d '{ "associatedSiteIds": ["c13254cd-1a3b-4945-bfb6-c33d02e7ff4b"] }' http://localhost:8080/getBuildingRiskAssessmentsBySite

Output:
```
[{"id":"dec2db38-7e83-45e8-a1d1-a2ee2967257c","createdAt":"2020-11-26T22:52:52.125","updatedAt":"2020-11-26T22:57:36.375","entityTrail":[{"timestamp":"2020-11-26T22:52:52.125","userId":"a2da8355-1429-4005-ba36-1f5cf45938af","systemComment":"CREATED BUILDING RISK ASSESSMENT"},{"timestamp":"2020-11-26T22:57:36.375","userId":"a2da8355-1429-4005-ba36-1f5cf45938af","systemComment":"UPDATED BUILDING RISK ASSESSMENT"}],"publisherId":"a2da8355-1429-4005-ba36-1f5cf45938af","riskAssessmentIds":["8c2bcb33-5665-47d4-a90b-4c6b2f06e065","2c744687-5c27-40ed-a92c-be0438b43455"],"buildingId":"048866c1-ff5b-4b5d-8aae-accb9337ff1f","title":"JBWS Building Assessment 2","description":"JBWS Building Assessment for COVID-19 protocols from OSHA and CDC"}]
```

/deleteRiskAssessment Input:
```
curl -i -X DELETE "http://localhost:8080/deleteBuildingRiskAssessment?id=fd8a0f3d-410f-47c3-8a91-419ad6b84929"
```

Output:
```
Deleted: BuildingRiskAssessments{id='fd8a0f3d-410f-47c3-8a91-419ad6b84929', createdAt=2020-11-26T23:04:39.251, updatedAt=2020-11-26T23:04:39.251, entityTrail=[EntityTrail{timestamp=2020-11-26T23:04:39.251, userId='a2da8355-1429-4005-ba36-1f5cf45938af', systemComment='CREATED BUILDING RISK ASSESSMENT'}], publisherId='a2da8355-1429-4005-ba36-1f5cf45938af', riskAssessmentIds=[8c2bcb33-5665-47d4-a90b-4c6b2f06e065, 2c744687-5c27-40ed-a92c-be0438b43455], buildingId='048866c1-ff5b-4b5d-8aae-accb9337ff1f', title='JBWN Building Assessment 1', description='JBWN Building Assessment for new HVAC filtration systems'} from building risk assessments repository
```

2020-11-26 23:37 UTC, GeoffA12 approved these changes

2020-11-27 08:25 UTC, merged