implemented update and delete
GeoffA12/building-risk-management-back-end pull request #4
Opened 2020-10-20 17:31 UTC by rfitzgerald11

2020-10-20 19:05 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/services/UserService.java
>  package com.cosc436002fitzarr.brm.services;
You'll need to fix the merge conflicts in this file. On line 29, it looks like you didn't commit some of the changes that were pushed into master branch for the /createUser API.

2020-10-20 19:07 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/services/SiteAdminUserService.java
> +        User updatedSiteAdminForPersistence = new User(
Why not,
`User updatedSiteAdmin = new SiteAdmin(...)` to be more specific here since this a `SiteAdmin` API?

2020-10-20 19:09 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/models/user/input/UpdateUserInput.java
> +    public UpdateUserInput(@JsonProperty SiteRole siteRole, @JsonProperty String firstName, @JsonProperty String lastName,
Shouldn't we get an existing SiteAdmin `ID` as part of the input object?

2020-10-20 19:10 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/controllers/SiteAdminController.java
There are some merge conflicts in this file you'll need to update and commit again. The /createSiteAdminUser has been removed in the master branch so you'll need to delete this code.

2020-10-20 19:11 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/models/user/input/ReferenceInput.java
> +        com.cosc436002fitzarr.brm.models.user.input.ReferenceInput that = (com.cosc436002fitzarr.brm.models.user.input.ReferenceInput) o;
Please remove import prefix here.

2020-10-20 19:12 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/services/SiteAdminUserService.java
> +            LOGGER.info("User " + updatedSiteAdminForPersistence.toString() + " saved in site repository");
We're saving to the `user` repository here, not the site repository.

2020-10-20 19:14 UTC, GeoffA12 commented on src/main/java/com/cosc436002fitzarr/brm/services/SiteAdminUserService.java
> +                input.getSiteRole(),
Eventually we'll need to check for null on these input fields. But for now this is fine.

2020-10-20 19:15 UTC, GeoffA12 requested changes
Left some comments for you to update in this branch.

2020-10-21 21:40 UTC, rfitzgerald11 commented
Creating a Site Admin (http://localhost:8080/createUser)
`{"siteRole": "SITEADMIN", "firstName": "Bruce", "lastName": "Wayne", "username": "BWayne", "email": "bwayne@stedwards.edu", "phone": "894-555-1983", "password": "Batman1939"}`
Response
`{"id":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","updatedAt":"2020-10-21T21:09:56.580275","createdAt":"2020-10-21T21:09:56.580275","entityTrail":[{"timestamp":"2020-10-21T21:09:56.580275","userId":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","systemComment":"CREATED SITE ADMIN USER"}],"publisherId":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","siteRole":"SITEADMIN","firstName":"Bruce","lastName":"Wayne","username":"BWayne","email":"bwayne@stedwards.edu","phone":"894-555-1983","authToken":"T8uF3tMYQeqaDZGLSCQVgV-x5ZlPgbVd","hashPassword":"��o)�\u0012�:�σmo6\u0013�"}`

Updating a Site Admin (http://localhost:8080/updateUser)
`{"id": "4816bdb9-2a5c-4fc2-942a-3f6994ba877f", "siteRole": "SITEADMIN", "firstName": "Clark", "lastName": "Kent", "username": "CKent", "email": "ckent@stedwards.edu", "phone": "532-091-1038", "authToken": "dhw8e7dhdhe7d1721928ssdawa", "hashPassword": "8dau9s8hdhsvdiu7sad9dsd"}`
Response
`{"id":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","updatedAt":"2020-10-21T21:13:03.9990823","createdAt":"2020-10-21T21:09:56.58","entityTrail":[{"timestamp":"2020-10-21T21:09:56.58","userId":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","systemComment":"CREATED SITE ADMIN USER"},{"timestamp":"2020-10-21T21:13:03.9990823","userId":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","systemComment":"UPDATED SITE ADMIN USER"}],"publisherId":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","siteRole":"SITEADMIN","firstName":"Clark","lastName":"Kent","username":"CKent","email":"ckent@stedwards.edu","phone":"532-091-1038","authToken":"dhw8e7dhdhe7d1721928ssdawa","hashPassword":"8dau9s8hdhsvdiu7sad9dsd"}`

Getting Users By Site Role (http://localhost:8080/getUsersBySiteRole?siteRole=SITEADMIN)
`{"siteRole": "SITEADMIN"}`
Response
`[{"id":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","updatedAt":"2020-10-21T21:09:56.58","createdAt":"2020-10-21T21:13:03.999","entityTrail":[{"timestamp":"2020-10-21T21:09:56.58","userId":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","systemComment":"CREATED SITE ADMIN USER"},{"timestamp":"2020-10-21T21:13:03.999","userId":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","systemComment":"UPDATED SITE ADMIN USER"}],"publisherId":"4816bdb9-2a5c-4fc2-942a-3f6994ba877f","siteRole":"SITEADMIN","firstName":"Clark","lastName":"Kent","username":"CKent","email":"ckent@stedwards.edu","phone":"532-091-1038","authToken":"dhw8e7dhdhe7d1721928ssdawa","hashPassword":"8dau9s8hdhsvdiu7sad9dsd"}]`

Deleting a User (http://localhost:8080/deleteUser)
`{"id": "4816bdb9-2a5c-4fc2-942a-3f6994ba877f"}`
Response
`User: User{id='4816bdb9-2a5c-4fc2-942a-3f6994ba877f', updatedAt=2020-10-21T21:09:56.580, createdAt=2020-10-21T21:13:03.999, entityTrail=[EntityTrail{timestamp=2020-10-21T21:09:56.580, userId='4816bdb9-2a5c-4fc2-942a-3f6994ba877f', systemComment='CREATED SITE ADMIN USER'}, EntityTrail{timestamp=2020-10-21T21:13:03.999, userId='4816bdb9-2a5c-4fc2-942a-3f6994ba877f', systemComment='UPDATED SITE ADMIN USER'}], publisherId='4816bdb9-2a5c-4fc2-942a-3f6994ba877f', siteRole=SITEADMIN, firstName='Clark', lastName='Kent', username='CKent', email='ckent@stedwards.edu', phone='532-091-1038', authToken='dhw8e7dhdhe7d1721928ssdawa', hashPassword='8dau9s8hdhsvdiu7sad9dsd'} deleted from the repository.`

2020-10-21 22:19 UTC, GeoffA12 approved these changes

2020-10-21 22:22 UTC, merged